### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Biostar-Ten** [InflexCZE/CreativeZone#4]
I've downloaded Patchzone into the Endzone folder. so:

Endzone/patchzone/doorstop.config, winhttp.dll, Patchzone folder/(contents of patchzone directory),including assets and mods folder. mod is listed in mods folder but doesn't work. After mod installation and activation, I exit and start game.

Deleted game, reinstalled and did the above again, still not working.
Newest compatible versions with the game
I probably did something not quite right...help

**Comment by InflexCZE** [comment]
Hey, sorry I somehow did not get notification for this issue.
`doorstop_config.ini` needs to be right next to the `Endzone.exe`, **not** in sub-folder.

CreativeZone is not compatible with latest version of EndZone, I'll try to address that asap.

**Comment by InflexCZE** [comment]
CreativeZone is updated and should work fine with latest EndZone again.

Let me know if you encounter any issues, otherwise I'll assume that all's fine and close this issue in a few days.

**Comment by Biostar-Ten** [comment]
If I extract patchzone.zip to endzone folder it comes out patchzone folder/patchzone folder/doorstop/winhttp. So I extract zip, open first folder and I copy patchzone folder/doorstop to endzone. Then I copy winhttp into the patchzone folder. 
patchzoneGUI/ addmod/github.com/InflexCZE/CreativeZone (no way to add a local mod)and it lists creative zone. click add again and it downloads it to mods folder. But the popup in patchzone to add mod stays up. x out and it shows no available mods or active mods and it is in the mods folder as 87d497aa-8410-444f-915f-54f7bb545a9b/creativezone.cs/creativezone.dll. and get this message as a txt
3/20/2021 6:27:42 PM
Loading Patch Zone
Startup inject
Loading mods
    Total known mods: 0
Mods loaded
PatchZone loading finished

Invoking OnBeforeGameStart for 0 mods
Invoke done

Installing registered service patches for 0 mods
Installation completed
Log closed

**Comment by Biostar-Ten** [comment]
Reading more carefully, after clicking add mod, it says Could not find file D\Gog Games\Endzone\Patchzone\Mods\87d.........\PatchZoneManifest.xml

**Comment by InflexCZE** [comment]
Of course, I messed up upload of the mod package, forgot to pack-in this file 😕 
Reuploaded, should be better now. 

Btw, "Local mods" function searches `PatchZone/Mods/*` for existing mods that are not yet known to the PatchZone.
This is useful if you obtain mod package from alternative source that is not known to the PatchZone automatic downloader.

**Comment by Biostar-Ten** [comment]
Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Biostar-Ten** [comment]
with it setup as Endzone\Patchzone\winhttp
Endzone\Dooorstop
it does not work. No errors, nothing
with it set up as Endzone\Patchzone
Endzone\Doorstop\Winhttp
It loads the first screen that says ENDONE with the O that fills up. Then BlackScreen with these errors.
[PatchZone.log](https://github.com/InflexCZE/CreativeZone/files/6178343/PatchZone.log)
[PatchZone_Debug.log](https://github.com/InflexCZE/CreativeZone/files/6178344/PatchZone_Debug.log)
[PatchZone_Error.log](https://github.com/InflexCZE/CreativeZone/files/6178345/PatchZone_Error.log)

**Comment by InflexCZE** [comment]
Logs say that PatchZone is initialized correctly, CreativeZone was loaded as well, but it can't find method `IEntityManager#Tick(float deltaTime, float unscaledTime, float systemScaled)` in the game. This one was added in one of the latest versions of the game.

My game (Steam) says version 1.0.7747.25951.
Can you check for me that you're running the same version of the game?
In case you're familiar with reflecting binaries, can you check for me that your game's `AfterTheEnd.dll` contains this method? Otherwise you can just attach it here and I can check it myself.

**Comment by Biostar-Ten** [comment]
Ouch. My mistake. Don't know how I missed that.

**Comment by Biostar-Ten** [comment]
Seems I was always trying to use it on the versions that weren't here.
It works now, but no creative zone splash screen thanks

**Comment by InflexCZE** [comment]
I know, they removed the Early Access banner that I hijacked 😇
